### ISSUE TITLE
Development 1.0.0 Release

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#100]
This is a compiled list of things to do before merging the [development](https://github.com/Arbitrium-Studios/Open-Fantasy/tree/development) branch with the [main](https://github.com/Arbitrium-Studios/Open-Fantasy/tree/main) branch:

- [ ] Reimplement [ToonTasks](https://github.com/Arbitrium-Studios/Open-Fantasy/tree/development_anesidora)
- [ ] Reimplement the Toontorial
- [ ] Reimplement [Holidays](https://github.com/Arbitrium-Studios/Open-Fantasy/tree/development_anesidora)
- [ ] Reimplement [Doodles](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/55)
- [ ] Reimplement [Fishing](https://github.com/Arbitrium-Studios/Open-Fantasy/tree/development_anesidora)
- [ ] Reimplement [Estates as a regular area](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/53)
- [ ] Finish [renaming the playgrounds in the files](https://github.com/Arbitrium-Studios/Open-Fantasy/tree/development_playground-renames)
- [ ] [Re-organize the root directory](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/58)
- [ ] Finish removing [all online functionality](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/56)
- [ ] Add the ability to create a [new issue](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/67) from within the game
- [ ] [Remove Loading Screens](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/68)

These are more necessary things to do which should take the top priority before anything else. Though, more things may be added on if needed.
