### ISSUE TITLE
Remove Online Functionality

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#56]
Remove all online functionality and requirements to make the game exclusively singleplayer.

**Comment by DarthMDev** [comment]
this will be very difficult heres what needs to be done:
remove astron, 
remove all uberdog and ai files but merge any server sided only stuff into client
remove all functions that send an update to the server and instead change it to do the server sided function

**Comment by GracieLovelight** [comment]
Thank you!

**Comment by GracieLovelight** [comment]
- [ ] Make all activities Games playable and maxable in singleplayer whether by adding AI opponents or reworking the activity

**Comment by GracieLovelight** [comment]
- [x] Make sure "removing" districts by hiding their code works without breaking the game
- [ ] Remove the Welcome Valley code cuz hiding most of it without removing it completely causes [Toons to go to the Shadow Realm](https://github.com/Arbitrium-Studios/Open-Fantasy/commit/b6a1077163c6727ddbe095e66c61c74b1b8faa14) and not be able to join.
- [ ] Remove all but 1 non-Welcome Valley District
- [ ] Remove the Districts page

**Comment by GracieLovelight** [comment]
Honestly, we might be reaching here. Since our goal right now is to just finish the reimplementation of some TTO features, we could just do the following and call it a day until we have the resources to actually pull something like this off.

- [ ] [Get News Locally](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/52)
- [ ] [Implement Doodles](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/55)
- [ ] [Implement the Toontorial](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/105)
- [ ] And maybe even [Convert images to PNG](https://github.com/Arbitrium-Studios/Open-Fantasy/issues/92) if we have the time

**Comment by GracieLovelight** [comment]
As for Astron, we could probably look into alternatives later down the line. I've had my eye on [OtpGo](https://github.com/LittleToonCat/OtpGo) for a bit but I'm not sure if it aligns with the project's goals.
